waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py
waveform-django/waveforms/templates/waveforms/annotations.html
waveform-django/waveforms/views.py

This change adds a new category for the annotator to review their annotations in which they may see any events they were unsure about. To qualify, the annotation must have been marked as "Uncertain". To help the user understand this new functionality, I adjusted the "Uncertain" radio button option to say "Uncertain / Save for later" to let the annotator know they may go back any time they wish via the links from the "Completed Annotations" list. I also adjusted the ordering of that page to now display "Uncertain / Save for later" annotations, then "Complete" annotations, and finally "Incomplete" annotations.

Adds uncertain / save for later category

---

waveform-django/waveforms/templates/waveforms/admin_console.html
waveform-django/waveforms/views.py

This change allows admins to adjust who are the other admins. To implement this, I added a button to the right side of the information listed for each user which states "Add admin" for users who are not already admins and "Remove admin" for user who already admins. Users can also adjust their own admin status so be careful! (remove buttons are in red to help reinforce... maybe I should have a "confirm" dialog also)
In the future, it would be nice to keep track of who is an admin on a per-project basis but I don't see us needing this for at least some time.

Allow admins to adjust admin control

---

waveform-django/waveforms/templates/waveforms/annotations.html
waveform-django/waveforms/views.py

This change fixes the errors in the number on the "Current Assignment" page. There were two problems:
1. The incomplete annotations had an extra row if you expand each record since the index it was referring to in the template was incorrect
2. The total number of annotations was incorrect since it did not take into account the assigned annotations to the user

Fixes annotation page numbers

---

.env.example
waveform-django/website/settings/base.py

This change makes it easier to switch between the settings used locally and in the production environments. The only step (which I've already taken) is to update the `.env` file on the production server to reflect its relative changes (email, logging, etc.).

Prevents manual switching between settings

---

waveform-django/waveforms/views.py

This change prevents events with no users assigned to them from being saved to the `user_annotations.csv` file. Steps to re-create this bug are:
1. Assign yourself annotations
2. Check the `user_annotations.csv` file and it should still be populated with the assigned events and with your username assigned to each
2. Revoke your annotations
3. Check the `user_annotations.csv` file and it should still be populated with the assigned events but this time with no users assigned to each

Prevents empty user assignments

---

waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py

This change allows less than 4 signals to display especially if a limited number are available (<4 overall, no BP, etc.).

Allows for less than 4 signals to display

---

waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py

This change discards signals which contains nearly all 0s instead of just all 0s. The purpose of this is because some channels may just be noise with very low amplitudes, therefore not all 0s.
In order to do this, I used a tolerance of 0.01 so any signal with all its values less than 0.01 will be discarded. I went through a bunch of signals to make sure this wouldn't cause any unintended consequences :)

Discards nearly all 0s signals

---

waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py

This change fixes the height of the annotation so it extends beyond the screen instead of just the initial view.

Fixes height of annotation

---

waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py

This change fixes a rare error which occurred when multiple initial signals are attempted to be removed due to all its values being less than 0.01.

Fixes rare error when removing sigs

---

waveform-django/waveforms/views.py

This change fixes the number of incomplete annotations displayed on the "View Assignment" page. Now, it shows the progress relative to each record as requested.
Fixes #35.

Fixes number of incomplete annotations #35

---

waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py

This change makes it so we can add new annotations which are not already in the standard format of 600 seconds total with the event at 300 seconds.

Makes annotation event flexible

---

waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py

This change prevents signals which have all the same value from being displayed.

Prevents all same sigs

---

waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py

This change removes the `CVP`, `ICP`, `LAP`, and `PAP` pressure signals as well as the `Resp` and `CO2` air signals as discussed.

Removes unnecessary signals

---

waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py
waveform-django/waveforms/templates/waveforms/annotations.html
waveform-django/waveforms/templates/waveforms/tutorial.html
waveform-django/waveforms/views.py

This change removes the "Uncertain" language on the "Save for Later" button to require annotators to complete all annotations with either a "True" or "False" in order to assign. It also keeps the "assign more annotations" form even when the user is not able to complete it to keep the page consistent.

Removes uncertain / clarifies language

---

waveform-django/waveforms/templates/waveforms/admin_console.html
waveform-django/waveforms/views.py

This change allows admins to link to any desired listed annotation on the admin console. This will help us investigate annotations with interesting comments and ones which created a lot of conflicts (some True, some False, etc.).

Adds link for admin annotations

---

waveform-django/waveforms/forms.py
waveform-django/waveforms/views.py
waveform-django/website/forms.py
waveform-django/website/settings/base.py
waveform-django/website/templates/registration/new_invite_email.html
waveform-django/website/templates/registration/new_invite_subject.txt
waveform-django/website/templates/registration/new_user_email.html
waveform-django/website/templates/registration/new_user_subject.txt
waveform-django/website/views.py

This change does three things:
1. Cleans the existing email functionalities by clarifying `https` usage and adding the send-from email to the settings.
2. Notifies admins when a new user joins.
3. Notifies admins when a new user is invited.

Adds email notifications for admins

---

waveform-django/waveforms/templates/waveforms/annotations.html
waveform-django/waveforms/views.py

This change fixes the warning on the Current Assignment page to be less disruptive. Previously, it displays any time the user has not completed their assignment but this change fixes it so that they are now only warned when they have saved an annotation as Save for Later.

Fixes current assignment warning

---

waveform-django/waveforms/templates/waveforms/leaderboard.html
waveform-django/waveforms/views.py

The number of events with two annotators and the number of events with one annotator can now be viewed on the leaderboard page.

Added event stats tracker to leaderboard

---

waveform-django/waveforms/views.py

This change fixes the bug in the leaderboard. Currently, it checks only that the dates have the same day, month, etc. which causes issues as soon as we get >month between annotations. This change fixes that to include the entire past week, month, etc. instead of just the matching one.

Fixes leaderboard date bug

---

waveform-django/waveforms/templates/waveforms/adjudicator_console.html

This change fixes the initial display position of the caliper and increases the margin allowing it to be stretched to the same as the typical waveform viewer.

Fixes adjudication caliper

---

waveform-django/waveforms/templates/waveforms/leaderboard.html
waveform-django/waveforms/views.py

This change adds a tracker for the number of conflicting annotations between annotators on the leaderboard page.

Adds conflicting annotation tracker

---

backups/README.md
requirements.txt
waveform-django/cron.py
waveform-django/website/settings/base.py

This change adds a `cronjob` to automatically download the latest annotations as a CSV file at midnight each night. Currently, it will only do the non-adjudicated ones but a future not-to-distant change will adjust this. I also fixed a bug in the static file delivery for `localhost` where the `STATIC_ROOT` was duplicated and I didn't realize because it was feeding off of my caches.

Adds cronjob / fixes local static

---

.env.example
.gitignore
README.md
deploy/etc/redis.conf
requirements.txt
waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py
waveform-django/website/settings/base.py

This change adds a stable cache to replace the current unstable default cache used by Django.
The issue was that the default cache provided by Django was unreliable especially across multiple sessions traditional with `nginx` which is the backend keeping the server running and the Django instance alive. I had naively thought that this could be fixed on the frontend which it kind of did but was still practically unusable so I started to look around at backend fixes. My solution was to implement my own cache using [Redis](https://redis.io) which is now a service running on the live server so that the waveform app can store its cache values there for each unique session / user instead of unreliably on the frontend as before.
The added benefit is that not only can the app store intermediate …

Adds stable cache

---

waveform-django/cron.py
waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py
waveform-django/waveforms/dash_apps/finished_apps/waveform_vis_adjudicate.py
waveform-django/waveforms/templates/waveforms/adjudicator_console.html
waveform-django/waveforms/templates/waveforms/annotations.html
waveform-django/waveforms/views.py

This change adds a functioning adjudication console. This change will allow pre-approved adjudicators to adjudicate waveforms which are completed (i.e., has at least two annotations) and conflicting (i.e., there is at least one decision disagreement between the completed annotation). This will show up as an `Adjudicator Console` tab at the top of the page.
It is assumed that the user would work together with fellow adjudicators to work through the conflicting events. At the top of the console will be all of the annotations for the given event. The adjudicator has the choice to mark the event as `True`, `False`, or `Uncertain` (meaning throw it out since it can't be determined --- *I don't actually throw it out*). Once the choice is made, a popup dialog will be displayed to confirm the …

Adds functioning adjudicator console

---

waveform-django/waveforms/dash_apps/finished_apps/waveform_vis_adjudicate.py
waveform-django/waveforms/templates/waveforms/adjudications.html
waveform-django/waveforms/templates/waveforms/adjudicator_console.html

This change adds the ability for adjudicators to add comments. Some bundled small fixes with this change is to make the annotations on the adjudicator console more visible my separating it from the viewer with a line. Second, I made adjudications red on the view adjudications page. Finally, I moved the caliper to a more convenient location when clicked on.

Adds adjudication comments

---

waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py
waveform-django/waveforms/dash_apps/finished_apps/waveform_vis_adjudicate.py
waveform-django/waveforms/templates/waveforms/adjudications.html
waveform-django/waveforms/templates/waveforms/adjudicator_console.html
waveform-django/waveforms/views.py

This change allows for adjudications to be edited and, by doing so, I removed the possibility for one to be adjudicated twice. Further, I sorted the adjudicates by most recent on the View Adjudications page.

Double adjudicate / sorted / editable

---

waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py

This change fixes the rendering of tough signals (i.e., signals with large range) and also re-centers the ticks around 0 instead of randomly generating an array of `grid_delta_major` resolution. This will not only make the rendering of the signals look better but also improve loading times since signals with large range previously took much longer to load due to the large number of ticks which had to be rendered.

Fixes rendering of tough signals

---

waveform-django/templates/base.html
waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py
waveform-django/waveforms/dash_apps/finished_apps/waveform_vis_adjudicate.py
waveform-django/waveforms/templates/waveforms/adjudicator_console.html
waveform-django/waveforms/templates/waveforms/home.html

This change switches the CSS from absolute to relative values to work better across multiple platforms and also allows the annotator to be responsive (yes it works but it's kinda ugly right now). I also filled up more of the screen so there's less whitespace now which enables better viewing of the waveforms.
This introduces a small issue of no longer being able to adjust the figure height/width from the settings but I don't think that will be a real issue ... will fix it sometime later.

Fixes CSS to be relative / improves graph display

---

waveform-django/waveforms/templates/waveforms/adjudications.html
waveform-django/waveforms/templates/waveforms/annotations.html
waveform-django/waveforms/views.py

This change fixes an `AttributeError` that was showing up (and flooding) the production logs but weren't caught locally for some reason ... anyway, the cause of the error was that `request.GET` was empty at initial load so `request.GET.complete_page` and `request.GET.incomplete_page` would return an `AttributeError` which would only go away after one of those request links (i.e., next page, previous page, show all, show pages) were clicked.

Fixes template pagination error

---

waveform-django/waveforms/views.py

This change fixes an error that occurs when there is an uneven amount of completed annotations by a single user. The error occurs when the number of events annotated by **ONLY** the user (which haven't been annotated by anyone else) is greater than the number of new events requested. This is because of #116 which adds the `set()` functionality which swallows these double assignments... which is good so this accounts for another edge case.

Fixes uneven assignments error

---

waveform-django/waveforms/templates/waveforms/admin_console.html
waveform-django/waveforms/templates/waveforms/annotations.html
waveform-django/waveforms/views.py
waveform-django/website/urls.py
waveform-django/website/views.py

The display of the admin console now shows a maximum of three records per category, with the option to scroll through pages. This should drastically improve the load times of the admin console.

Paginated Admin Console
