MIT-LCP/waveform-annotation

- waveform-django/waveforms/templates/waveforms/admin_console.html
- waveform-django/waveforms/templates/waveforms/annotations.html
- waveform-django/waveforms/templates/waveforms/home.html
- waveform-django/waveforms/templates/waveforms/leaderboard.html
- waveform-django/waveforms/templates/waveforms/settings.html
- waveform-django/waveforms/templates/waveforms/tutorial.html
- waveform-django/waveforms/urls.py
- waveform-django/waveforms/views.py
Leaderboard and Statistics tab displays detailed info about how many annotations users
made during a certain span of time. A user can view their own statistics, as well
as a global leaderboard which displays the top 10 users for each category
Also updates text on the tab bar to be more clear
> Added Leaderboard and Statistics Tab

- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py
This change attempts to replace empty signals (being defined as those with all 0s) with the next signal in the priority list. If that signal is also empty, then repeat the process.
> Attempts to replace empty signals

- waveform-django/waveforms/forms.py
This change allows admin users to resend emails to those who have already been previously invited. This also fixes the naive timezone warning which kept coming up since timezones are turned on and I was assigning dates without timezone.
> Fixes duplicate email bug / timezone error

- waveform-django/waveforms/views.py
Events are now randomly assigned to users. A project is randomly selected out of all available projects,
and events are randomly selected from this project. This process loops until the requested number of events has been assigned.
> Create random assignments

- waveform-django/waveforms/templates/waveforms/admin_console.html
- waveform-django/waveforms/views.py
Allows admins to output all the completed annotations as a CSV file with:
1. Username
2. Record
3. Event
4. Decision
5. Comments
6. Decision Date
Fixes #10.
> Output annotations as CSV #10

- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py
This change improves the sorting of the signals displayed by:
1. Showing incomplete annotations first
2. Then "Save for Later" annotations
3. Finally, complete annotations
I think, in the process, I also fixed the issue where the incorrect signal was rendered if it was requested or "edited" from the "Current Annotations" tab.
> Improves sorting of signals

- waveform-django/waveforms/views.py
Assignment now prioritizes events that have other users assigned to them.
Site will first go through all events with a member assigned and add assignments to those events.
When no such events are left, events are then completely randomly assigned: each event is selected
by randomly choosing a project and then randomly choosing an event within that project.
> Changed random assignment method

- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py
This change adds the new signal names from the various signal sources.
> Adds new signals

- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py
- waveform-django/waveforms/views.py
This change makes it so that all the possible events for the selected project are displayed for admin users. This prevents us from having to assign ourselves events.
> Displays all events for admins

- waveform-django/waveforms/views.py
This change fixes a bug which occurred when multiple users were being assigned to the same event.
> Accounts for multiple assignees

- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py
This change improves the appearance of the hover line by removing the label, making it thinner, and switching from dashes to dots.
> Improves hover line appearance

- record-files/2015_data/filter_anns.sh
- record-files/2021_data/filter_anns.sh
Events are chosen at random. Must rerun filter_ann.sh.
> Updated bash script so that no more than 5 events can be selected from same record

- waveform-django/waveforms/templates/waveforms/home.html
This change increases the size of the hit box for resizing the caliper.
> Increases size of caliper drag margin

- waveform-django/waveforms/templates/waveforms/leaderboard.html
- waveform-django/waveforms/views.py
> Fixes leaderboard date bug

- requirements.txt
- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py
This change should improve the feature which allows users to request specific events to view. This issue wasn't reproduced locally since I believe it was more client-sided since it depended heavily on browser type but these changes should address these (my theory was right about [inconsistent loading times](https://github.com/GibbsConsulting/django-plotly-dash/commit/240f62c2b9bb2606debb9f3e0bb35437cb509377)). Hopefully this solves the issue or at least makes it better!
> Improves ann request / updates requirements

- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py
- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis_adjudicate.py
This change improves the default visualization of EKG signals by removing their requirement to be on the same scale. Now, if one EKG signal has a high amplitude and one has a low amplitude they will be shown on difference scales relative to their range of values, whereas before they would be on the same scale so the lower amplitude signal would be difficult to visualize.
> Improves EKG signal display

- waveform-django/waveforms/views.py
This change fixes the assignment start date to be update with each new assignment instead of just once for the first one.
> Fixes assignment start date

- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py
- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis_adjudicate.py
This change refactors the code for the waveform viewer to remove redundancies leftover from its origin as a PhysioNet waveform viewer.
> Refactors waveform viewer

- waveform-django/waveforms/templates/waveforms/leaderboard.html
- waveform-django/waveforms/views.py
Previously there was an error when getting randomly assigned events when there was not enough events remaining to assign to meet the requested amount. I have refactored the code to better handle this situation.
> Fix Assignment Bug

- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis_adjudicate.py
This change adds a next button for the adjudicator in order to skip the current annotation if the current adjudicator was one of the annotators or the other annotator isn't available for joint review.
> Adds next button for adjudicator

- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis_adjudicate.py
- waveform-django/waveforms/views.py
This change improves the loading speed of the adjudication pages .. not sure by exactly how much but for locally the improvement was about half of the loading time so we'll see on the live server.
I plan to use the same techniques for the other pages to improve their speeds as well especially for the slower ones like viewing current annotations, etc.
> Improves speed of adjudications

- waveform-django/waveforms/templates/waveforms/adjudications.html
- waveform-django/waveforms/templates/waveforms/annotations.html
- waveform-django/waveforms/views.py
This change adds pages and a search feature to the adjudications.
> Adds pages and search to adjudications

- waveform-django/waveforms/views.py
This change adds adjudications to the CSV download on the admin console.
> Adds adjudications to CSV download

- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis_adjudicate.py
- waveform-django/waveforms/models.py
- waveform-django/waveforms/views.py
This change optimizes the speed of some of the queries. There are still ways I can speed up the code so consider this a Part 1.
> Optimizes the speed of some queries

- waveform-django/waveforms/templates/waveforms/leaderboard.html
This change cleans some styling up and switches the pie chart from percentages to values.
> Cleans / switches pie chart to values

- record-files/2015_data/filter_anns.sh
- record-files/2015_data/sub_records.sh
- record-files/2015_data/top_records.sh
- record-files/2021_data/filter_anns.sh
- record-files/2021_data/sub_records.sh
- record-files/2021_data/top_records.sh
- record-files/merge_new_data.sh
This changes creates some shell scripts to help automate the merging of new data. Documentation will come next!
> Automates merging of new data

- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py
- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis_adjudicate.py
- waveform-django/waveforms/templates/waveforms/adjudicator_console.html
- waveform-django/waveforms/templates/waveforms/home.html
This change adjusts the size of the annotator to be smaller to make it easier to view the waveforms holistically.
> Adjusts size of annotator

- waveform-django/cron.py
This changes starts tracking adjudications in the backup CSV file.
> Adds adjudications to backup file

- waveform-django/cron.py
- waveform-django/export/tests.py
- waveform-django/schema.py
- waveform-django/templates/base.html
- waveform-django/waveforms/apps.py
- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py
- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis_adjudicate.py
- waveform-django/waveforms/forms.py
- waveform-django/waveforms/models.py
- waveform-django/waveforms/urls.py
- waveform-django/waveforms/views.py
- waveform-django/website/forms.py
- waveform-django/website/templates/website/login.html
- waveform-django/website/tokens.py
- waveform-django/website/urls.py
- waveform-django/website/views.py
This change adds docstrings to the script files for the tool ... the next step is to add supporting documentation for the template files.
> Adds docstrings to functions

- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis.py
- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis_adjudicate.py
- waveform-django/waveforms/dash_apps/finished_apps/waveform_vis_tools.py
This change merges the two current waveform display apps (one for annotating and one for adjudication) by combining shared functions and workflows. This will prevent issues later on where we have to edit the same thing twice between the two apps (such as a change in how we determine the y-axis limits). It also cleans up the repo and may make the annotator slightly faster.
> Merges /refactors waveform apps
